services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "14317:4317"   # OTLP gRPC Collector
      - "4318:4318"   # OTLP HTTP Collector
      - "55680:55680" # Porta comum para OTLP
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # UI do Jaeger
      - "4317:4317"    # OTLP gRPC port
      - "14250:14250"  # Porta gRPC para o Jaeger Collector
      - "14268:14268"  # Porta HTTP para o Jaeger Collector
      - "6831:6831/udp" # Porta UDP para agentes Jaeger

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "32789:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
