receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: "jaeger:4317"  # Use OTLP gRPC port
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"  # Exposição de métricas para Prometheus

processors:
  batch:  # Melhora a performance e reduz a carga no sistema

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
