{
 "title": "eShop Metrics",
 "time": { "from": "2025-03-11T00:36:41.241Z", "to": "2025-03-11T02:36:41.241Z" },
 "panels": [
  {
   "title": "System / Host Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Usei dotnet_process_cpu_time_seconds_total em conjunto com a taxa (rate) para ver o consumo de CPU ao longo do tempo",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(dotnet_process_cpu_time_seconds_total[1m])\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Working Set",
     "type": "timeseries",
     "description": "dotnet_process_memory_working_set_bytes (mostra memória em uso pela aplicação)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "dotnet_process_memory_working_set_bytes\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC Collections",
     "type": "timeseries",
     "description": "Permite-me ver quantas coletas de garbage collector estão a ocorrer em cada uma das gerações.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "increase(dotnet_gc_collections_total[5m])\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ASP.NET Core / HTTP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "timeseries",
     "description": "Para ver a quantidade de requisições por segundo:",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by (method, route) (\n  rate(http_server_request_duration_seconds_count[1m])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\n  sum by (le) (\n    rate(http_server_request_duration_seconds_bucket[5m])\n  )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active HTTP Requests",
     "type": "gauge",
     "description": "Mostra quantas requisições estão ativamente em processamento no momento.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "http_server_active_requests", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Custom eShop Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Orders Placed",
     "type": "stat",
     "description": "Ver o valor acumulativo atual",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "order_placed_count_total\n", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Order Value (Somatório)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rate(order_value_total[5m])", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Order Query p95 Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\n  sum by (le) (\n    rate(order_query_latency_ms_milliseconds_bucket[5m])\n  )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}